### ISSUE TITLE
How can I send a message?

### ISSUE THREAD

**Issue by pbeneteau** [realtime-framework/MessagingSwiftChat#5]
When I build and run the app I can't send any message to other "user". There is no option to do that. What should I do? thx

**Comment by pbeneteau** [comment]
May be I have to join a room chat that already exist? But I can't create any room: it cras.

**Comment by realtime-framework** [comment]
Yes, you need to create a channel first.

Tap "Edit" from the top right corner > Enter the channel name in the input field > Tap the green + icon >Tap Done on the top right corner > Tap the new channel name to enter the chat room > Tap the top edit icon to compose a new message > Tap Save to send the message

This should work. Please let us know if it doesn't.
Thanks.

**Comment by pbeneteau** [comment]
why are the messages getting deleted?

**Comment by realtime-framework** [comment]
Realtime Messaging doesn't persist messages, you need to save them in your own database.
